
export MATRIX_SERVER="https://matrix.org/"

# The room ID where the message should be posted (not the room alias).
# https://matrix.org/docs/older/client-server-api/#creating-a-room
export MATRIX_ROOM_ID=""

# Authentication Token from the account that posts the messages.
# https://matrix.org/docs/older/client-server-api/#registration
# Therefore, this file should be kept secret! chmod 0600 matrix.conf
export MATRIX_TOKEN=""
