.TH NEEDRESTART "1" "August 2013" "needrestart " "User Commands"
.SH NAME
needrestart \- needrestart
.SH DESCRIPTION
needrestart checks which daemons need to be restarted after library upgrades.
.SH USAGE
Usage:
.IP
needrestart [\-vn] [\-c <cfg>] [\-r <mode>] [\-bkl]
.TP
\fB\-v\fR
be more verbose
.TP
\fB\-n\fR
set default answer to 'no'
.TP
\fB\-c\fR <cfg>
config filename
.TP
\fB\-r\fR <mode>
set restart mode
.TP
l
(l)ist only
.TP
i
(i)nteractive restart
.TP
a
(a)utomatically restart
.TP
\fB\-b\fR
enable batch mode
.PP
By using the following options only the specified checks are performed:
.TP
\fB\-k\fR
check for obsolete kernel
.TP
\fB\-l\fR
check for obsolete libraries
.SH "AUTHOR"
Thomas Liske <thomas@fiasko\-nw.net>
.SH "COPYRIGHT"
2013 - 2014 (C) Thomas Liske [http://fiasko\-nw.net/~thomas/]
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.SH "UPSTREAM"
https://github.com/liske/needrestart
