.TH NEEDRESTART "1" "January 2015" "needrestart " "User Commands"
.SH NAME
needrestart \- needrestart
.SH DESCRIPTION
needrestart checks which daemons need to be restarted after library upgrades.
.SH USAGE
Usage:
.IP
needrestart [\-(v|q)] [\-n] [\-c <cfg>] [\-r <mode>] [\-f <fe>] [\-u <ui>] [\-(b|p)] [\-kl]
.TP
\fB\-v\fR
be more verbose
.TP
\fB\-q\fR
be quiet
.TP
\fB\-m\fR <mode>
set level of technical details
.TP
   e
(e)asy mode
.TP
   a
(a)dvanced mode
.TP
\fB\-n\fR
set default answer to 'no'
.TP
\fB\-c\fR <cfg>
config filename
.TP
\fB\-r\fR <mode>
set restart mode
.TP
   l
(l)ist only
.TP
   i
(i)nteractive restart
.TP
   a
(a)utomatically restart
.IP
\fBATTENTION:\fR If needrestart is configured to run in interactive mode but is run non-interactive (i.e. unattended-upgrades) it will fallback to list only mode.
.TP
\fB\-b\fR
enable batch mode
.TP
\fB\-p\fR
nagios plugin mode: makes output and exit codes nagios compatible
.TP
\fB\-f\fR <fe>
overwrite debconf(7) frontend, sets the DEBIAN_FRONT environment variable to <fe>
.TP
\fB\-u\fR <ui>
use preferred UI package (-u ? shows available packages)
.PP
By using one of the following options only the specified checks are performed:
.TP
\fB\-k\fR
check for obsolete kernel
.TP
\fB\-l\fR
check for obsolete libraries
.SH ENVIRONMENT
The following environment variables can be used to override the config file options. Command line parameters do always supersede them.
.TP
\fBNEEDRESTART_MODE\fR
Change the configured restart mode (see also the \fB\-r\fR parameter): (l)ist only, (i)nteractive or (a)utomatically
.RE

When used with apt-get(8) needrestart supports the following additional environment variables:
.TP
\fBDEBIAN_FRONT\fR
The debconf(7) frontend to use, can also set using the \fB\-f\fR parameter.
.TP
\fBNEEDRESTART_SUSPEND\fR
If set to a non-empty value the apt-get(8) hook will not run needrestart after installing or updating packages.
.SH "AUTHOR"
Thomas Liske <thomas@fiasko\-nw.net>
.SH "COPYRIGHT"
2013 - 2018 (C) Thomas Liske [http://fiasko\-nw.net/~thomas/]
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.SH "UPSTREAM"
https://github.com/liske/needrestart
