.TH NEEDRESTART "1" "August 2013" "needrestart " "User Commands"
.SH NAME
needrestart \- needrestart
.SH DESCRIPTION
needrestart 0.2 \- Restart daemons after library updates.
.SS "Authors:"
.IP
Thomas Liske <thomas@fiasko\-nw.net>
.SH COPYRIGHT
.SS "Copyright Holder:"
.IP
2013 (C) Thomas Liske [http://fiasko\-nw.net/~thomas/]
.SS "Upstream:"
.IP
https://github.com/liske/needrestart
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
Usage:
.IP
needrestart [\-vn] [\-c <cfg>] [\-r <mode>]
.TP
\fB\-v\fR
be more verbose
.TP
\fB\-n\fR
set default answer to 'no'
.TP
\fB\-c\fR <cfg>
config filename
.TP
\fB\-r\fR <mode>
set restart mode
.TP
l
(l)ist only
.TP
i
(i)nteractive restart
.TP
a
(a)utomatically restart
.TP
\fB\-b\fR
enable batch mode
.PP
needrestart 0.2 \- Restart daemons after library updates.
.SS "Authors:"
.IP
Thomas Liske <thomas@fiasko\-nw.net>
.SS "Copyright Holder:"
.IP
2013 (C) Thomas Liske [http://fiasko\-nw.net/~thomas/]
.SS "Upstream:"
.IP
https://github.com/liske/needrestart
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
