#!/bin/sh

# needrestart - Restart daemons after library updates.
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2013 - 2015 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#

# Use write to notify users on TTYs.

case "$NR_SESSION" in
    /dev/tty*|/dev/pts*)
	echo "[$0] notify user $NR_USERNAME on $NR_SESSION" 1>&2
	{
	    echo
	    echo "Your session is running obsolete binaries or libraries as listed below."
	    echo "Please consider to relogin or restart them!"
	    echo
	    cat
	    echo
	} | write "$NR_USERNAME" "$NR_SESSION" 2> /dev/null
	;;
    *)
	echo "[$0] skip session w/o tty" 1>&2
	exit 1;
	;;
esac
