#!/bin/sh

RUNDIR=/var/run/needrestart

# dpkg had an error... exit silently
if [ -e "$RUNDIR/errored" ]; then
    echo "needrestart is being skipped since dpkg has failed"
    rm -f "$RUNDIR/errored"
    exit 0
fi

if [ -e "$RUNDIR/unpacked" ]; then
    rm -f "$RUNDIR/unpacked"
    exec /usr/sbin/needrestart
fi
