#!/bin/sh

# needrestart - Restart daemons after library updates.
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2013 - 2020 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#

RUNDIR=/run/needrestart

mkdir -p "$RUNDIR"

touched=0
errored=0

while read tag p0 p1 p2 p3 p4 pp; do
    if [ "$tag" = 'status:' ] && [ "$p1" = 'unpacked' ]; then
        if [ "$touched" = 0 ]; then
            touch "$RUNDIR/unpacked"
            touched=1
        fi
    else
        if [ "$tag" = 'status:' ] && \
            [ "$p1" = ':' ] && \
            [ "$p2" = 'error' ] && \
            [ "$p3" = ':' ]; then
            if [ "$errored" = 0 ]; then
                touch "$RUNDIR/errored"
                errored=1
            fi
        fi
    fi
done
