#!/usr/bin/perl

# needrestart - Restart daemons after library updates.
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2013 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# This DPKG hook tries to find the run-level scripts of the package's binary
# which has old libraries in use. Some logic is taken from the checkrestart
# (part of the debian-goodies package) package by Matt Zimmerman <mdz@debian.org>,
# Javier Fernandez-Sanguino <jfs@debian.org> et. al.

use strict;
use warnings;

sub fork_dpkg(@) {
    my $pid = open(HDPKG, '-|');
    defined($pid) || die "Can't fork: $!\n";

    if($pid == 0) {
	close(STDIN);
	close(STDERR);

	exec(@_);
	exit;
    }

    \*HDPKG
}

my $FN = shift || die "Usage: $0 <filename>\n";
my $psearch = fork_dpkg(qq(dpkg-query --search $FN));

my @pkgs;
while(<$psearch>) {
    chomp;

    next if(/^local diversion/);
    next unless(/:/);

    next unless(/([^:]+): $FN$/);

    push(@pkgs, $1);
}
close($psearch);

exit(0) unless($#pkgs > -1);

foreach my $pkg (@pkgs) {
    print "dpkg|PACKAGE|$pkg\n";

    my $plist = fork_dpkg(qq(dpkg-query --listfiles $pkg));
    while(<$plist>) {
	print "dpkg|RC|$1\n" if(m@^/etc/init.d/(.+)$@);
    }
    close($plist);
}

exit(1);
