#!/usr/bin/perl

# needrestart - Restart daemons after library updates.
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2013 - 2020 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# This DPKG hook tries to find the run-level scripts of the package's binary
# which has old libraries in use. Some logic is taken from the checkrestart
# (part of the debian-goodies package) package by Matt Zimmerman <mdz@debian.org>,
# Javier Fernandez-Sanguino <jfs@debian.org> et. al.

use Getopt::Std;

use strict;
use warnings;

system("type dpkg-query 1> /dev/null 2> /dev/null");
exit 0 if ($? != -1 && $? >> 8);

our $opt_v;
getopts('v');

sub fork_pipe(@) {
    my $pid = open(HPIPE, '-|');
    defined($pid) || die "Can't fork: $!\n";

    if($pid == 0) {
	close(STDIN);
	close(STDERR) unless($opt_v);

	exec(@_);
	exit;
    }

    \*HPIPE
}

my $FN = shift || die "Usage: $0 <filename>\n";
my $psearch = fork_pipe(qw(dpkg-query --search), $FN);

my @pkgs;
while(<$psearch>) {
    chomp;

    next if(/^local diversion/);
    next unless(/:/);

    next unless(/(\S+): $FN$/);

    push(@pkgs, $1);
}
close($psearch);

exit(0) unless($#pkgs > -1);

foreach my $pkg (@pkgs) {
    print "PACKAGE|$pkg\n";

    my $plist = fork_pipe(qw(dpkg-query --listfiles), $pkg);
    while(<$plist>) {
        chomp;
        print "RC|$1\n" if(m@^/etc/init.d/(.+)$@ && -x $_);
    }
    close($plist);
}

exit(1);
