#!/usr/bin/perl

# needrestart - Restart daemons after library updates.
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2013 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# This RPM hook tries to find the run-level scripts of the package's binary
# which has old libraries in use.

use Getopt::Std;

use strict;
use warnings;

our $opt_v;
getopts('c:v');

sub fork_pipe(@) {
    my $pid = open(HPIPE, '-|');
    defined($pid) || die "Can't fork: $!\n";

    if($pid == 0) {
	close(STDIN);
	close(STDERR) unless($opt_v);

	undef $ENV{LANG};

	exec(@_);
	exit;
    }

    \*HPIPE
}

my $FN = shift || die "Usage: $0 <filename>\n";
my $psearch = fork_pipe(qq(rpmquery --file $FN));

my @pkgs;
while(<$psearch>) {
    chomp;

    next if(/^file .+ is not owned by any package/);

    push(@pkgs, $_);
}
close($psearch);

exit(0) unless($#pkgs > -1);

foreach my $pkg (@pkgs) {
    print "PACKAGE|$pkg\n";

    my $plist = fork_pipe(qq(rpmquery --filesbypkg $pkg));
    while(<$plist>) {
	print "RC|$2\n" if(m@^\S+\s+/etc(/rc\.d)?/init\.d/(.+)$@);
    }
    close($plist);
}

exit(1);
