#!/usr/bin/perl

# needrestart - Restart services after library updates.
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2013 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# This DPKG hook tries to find the run-level scripts of the package's binary
# which has old libraries in use. Some logic is taken from the checkrestart
# (part of the debian-goodies package) package by Matt Zimmerman <mdz@debian.org>,
# Javier Fernandez-Sanguino <jfs@debian.org> et. al.

use strict;
use warnings;

my $FN = shift;

my $pid = open(HDPKG, '-|');
defined($pid) || die "Can't fork: $!\n";

if($pid == 0) {
    close(STDIN);
    close(STDERR);

    exec('dpkg-query', '--search', $FN);
    exit;
}

my @pkgs;
while(<HDPKG>) {
    chomp;

    next if(/^local diversion/);
    next unless(/:/);

    next unless(/([^:]+): $FN$/);

    push(@pkgs, $1);
}

print "R: ",join(', ', @pkgs),"\n";
