#!/bin/sh

# needrestart - Restart daemons after library updates.
#
# Restarting systemd using special systemctl call.
#

# enable xtrace if we should be verbose
if [ "$NR_VERBOSE" = '1' ]; then
    set -x
fi

exec systemctl daemon-reexec
